AWS_ACCESS_KEY = "You AWS Access Key"
AWS_SECRET_KEY = "Your AWS Secret Key"
AWS_REGION = "us-east-1" #leave default
AWS_USERID = "You AWS used ID"
MYSQL_USERNAME = "exampleuser" #leave default
MYSQL_PASSWORD = "examplepass" #leave default
MYSQL_DB = "ebdb" #leave default
SSH_PUBLIC_KEY = "~/.ssh/id_rsa.pub" #leave default for mac
S3BUCKET = "You Bucket name"